# Generated by Django 3.2 on 2022-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('Roll_No', models.CharField(max_length=50, null=True)),
                ('Student_ID', models.CharField(max_length=50, null=True)),
                ('dOB', models.DateField(null=True)),
                ('Course', models.CharField(choices=[('BCA', 'BCA'), ('Masters', 'Masters'), ('B.Tech', 'B.Tech'), ('BBA', 'BBA')], max_length=50, null=True)),
                ('Stream', models.CharField(choices=[('EE', 'EE'), ('IT', 'IT'), ('CSE', 'CSE'), ('ME', 'ME'), ('CE', 'CE'), ('FT', 'FT'), ('ECE', 'ECE'), ('NONE', 'NONE')], max_length=50, null=True)),
                ('Mobile_No', models.IntegerField(null=True)),
                ('Address', models.TextField(max_length=150, null=True)),
                ('percentage_10th', models.IntegerField(null=True)),
                ('percentage_12th', models.IntegerField(null=True)),
            ],
        ),
    ]
